### ISSUE TITLE
Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by jrcacd** [kobeumut/UpdateChecker#3]
```
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - Android Studio 3.1  Build #AI-173.4670197 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_152-release 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - OS: Windows 10 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorPaste 
2018-04-03 09:47:29,416 [J pool 1/3]  ERROR - aemon.impl.PassExecutorService - Resolver for 'project source roots and libraries for platform JVM' does not know how to resolve [] 
java.lang.AssertionError: Resolver for 'project source roots and libraries for platform JVM' does not know how to resolve []
	at org.jetbrains.kotlin.analyzer.ResolverForProjectImpl.diagnoseUnknownModuleInfo(AnalyzerFacade.kt:194)
	at org.jetbrains.kotlin.idea.caches.resolve.ProjectResolutionFacade.resolverForElement(ProjectResolutionFacade.kt:161)
	at org.jetbrains.kotlin.idea.caches.resolve.ResolutionFacadeImpl.tryGetFrontendService(ResolutionFacadeImpl.kt:87)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.getJavaDescriptorResolver(JavaResolveExtension.kt:106)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.getJavaFieldDescriptor(JavaResolveExtension.kt:60)
	at org.jetbrains.kotlin.idea.caches.resolve.util.JavaResolutionUtils.getJavaMemberDescriptor(JavaResolveExtension.kt:68)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.processJvmCallablesByName(KotlinIndicesHelper.kt:261)
	at org.jetbrains.kotlin.idea.quickfix.ImportFix.collectMemberCandidates(ImportFix.kt:335)
	at org.jetbrains.kotlin.idea.quickfix.ImportFix.fillCandidates(ImportFix.kt:363)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestionsForName(ImportFix.kt:178)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestions(ImportFix.kt:148)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.computeSuggestions(ImportFix.kt:94)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$Factory.createAction(ImportFix.kt:231)
	at org.jetbrains.kotlin.idea.quickfix.KotlinSingleIntentionActionFactory.doCreateActions(KotlinSingleIntentionActionFactory.kt:25)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActions(KotlinIntentionActionsFactory.kt:53)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActionsForAllProblems(KotlinIntentionActionsFactory.kt:35)
	at org.jetbrains.kotlin.idea.highlighter.KotlinPsiCheckerKt.createQuickFixes(KotlinPsiChecker.kt:125)
	at org.jetbrains.kotlin.idea.highlighter.KotlinPsiCheckerKt.access$createQuickFixes(KotlinPsiChecker.kt:1)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.setUpAnnotations(KotlinPsiChecker.kt:274)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticAnnotations(KotlinPsiChecker.kt:269)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsAnnotations(KotlinPsiChecker.kt:200)
	at org.jetbrains.kotlin.idea.highlighter.KotlinPsiChecker.annotateElement(KotlinPsiChecker.kt:96)
	at org.jetbrains.kotlin.idea.highlighter.KotlinPsiChecker.annotate(KotlinPsiChecker.kt:76)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1130)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by mrfanatic** [comment]
for me, my error is:

```
Manifest merger failed : Attribute application@theme value=(@style/MyStyle) from AndroidManifest.xml:23:9-39
	is also present at [com.github.kobeumut:UpdateChecker:0.1.3] AndroidManifest.xml:20:9-40 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:17:5-58:19 to override.
```

**Comment by dondeepak** [comment]
i am also getting same error : 
Manifest merger failed : Attribute application@theme value=(@style/AppTheme.NoActionBar) from AndroidManifest.xml:29:9-52
	is also present at [com.github.kobeumut:UpdateChecker:0.1.3] AndroidManifest.xml:20:9-40 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:24:5-82:19 to override.

**Comment by kobeumut** [comment]
I'll check soon and I'll get a new version

**Comment by jrcacd** [comment]
WE need to use this good library, but we are wating for the bug fixes.

**Comment by jrcacd** [comment]
When a fix will be released?

**Comment by kobeumut** [comment]
I've solved the errors above. can you please try again on new version? I am sorry for the delay. Fixed 0.2.0

**Comment by jrcacd** [comment]
> Task :transformClassesAndResourcesWithR8ForRelease FAILED
AGPBI: {"kind":"error","text":"Program type already present: com.android.volley.RequestQueue","sources":[{}],"tool":"R8"}

- Execution failed for task transformClassesAndResourcesWithR8ForRelease'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

**Comment by kobeumut** [comment]
Sorry my mistake, I deleted volley but some codes which import volley stay in code. So I deleted and fix this issue please try new version.

**Comment by jrcacd** [comment]
This is fixed, thanks

**Comment by kobeumut** [comment]
Your welcome
